### ISSUE TITLE
Flag doesn't work for address

### ISSUE THREAD

**Issue by off-bank** [alfg/bithook#1]
Somehow the -webhook flag works for new blocks (bithook blocks -webhook=http://webhook/path), but it doesn't for address subscription, as in
bithook address 1xxxxxxxx -webhook=http://webhook/path
I've changed the code to parse the url as an arg (not a flag), and it works fine. 
What could be wrong?

**Comment by alfg** [comment]
Hi @off-bank, 

Sorry for the late response. According to https://golang.org/pkg/flag/:
> Flag parsing stops just before the first non-flag argument ("-" is a non-flag argument) or after the terminator "--".

I updated the code to check if the last argument is a url and use that as the webhook. So the following example should now work:
`bithook address 1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp http://requestb.in/nt5bcnnt`

Thanks for reporting this!
